### ISSUE TITLE
TypeError: e.store.getVCFHeader is not a function

### ISSUE THREAD

**Issue by srobb1** [elsiklab/multivariantviewer#25]
Hello,

I am getting an error when diplaying a MultiVariantViewer/View/Track/Grid . I am not sure when this started. I have not check these tracks for a while and I have done an upgrade or two since my last look. I am currently running JBrowse 1.16.6.

![Screen Shot 2019-11-20 at 10 49 57 AM](https://user-images.githubusercontent.com/1072991/69263941-8f3d4500-0b83-11ea-9043-37446a048360.png)

```
0.bundle.js:14 TypeError: e.store.getVCFHeader is not a function
    at 1.bundle.js:1
    at u (0.bundle.js:1)
    at c.then.h.then (0.bundle.js:1)
    at Object.makeTrackLabel (1.bundle.js:1)
    at Object.setViewInfo (1.bundle.js:1)
    at Object.d (0.bundle.js:1)
    at Object.setViewInfo (1.bundle.js:1)
    at Object.<anonymous> (1.bundle.js:1)
    at 0.bundle.js:1
    at 1.bundle.js:1 "TypeError: e.store.getVCFHeader is not a function
    at https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:828650
    at u (https://simrbase.stowers.org/jbrowse/dist/0.bundle.js:1:41141)
    at c.then.h.then (https://simrbase.stowers.org/jbrowse/dist/0.bundle.js:1:42531)
    at Object.makeTrackLabel (https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:828626)
    at Object.setViewInfo (https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:263250)
    at Object.d (https://simrbase.stowers.org/jbrowse/dist/0.bundle.js:1:13514)
    at Object.setViewInfo (https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:320524)
    at Object.<anonymous> (https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:514073)
    at https://simrbase.stowers.org/jbrowse/dist/0.bundle.js:1:20377
    at https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:514577
    ----------------------------------------
    rejected at d (https://simrbase.stowers.org/jbrowse/dist/0.bundle.js:1:41576)
    at u (https://simrbase.stowers.org/jbrowse/dist/0.bundle.js:1:41291)
    at c.then.h.then (https://simrbase.stowers.org/jbrowse/dist/0.bundle.js:1:42531)
    at Object.makeTrackLabel (https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:828626)
    at Object.setViewInfo (https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:263250)
    at Object.d (https://simrbase.stowers.org/jbrowse/dist/0.bundle.js:1:13514)
    at Object.setViewInfo (https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:320524)
    at Object.<anonymous> (https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:514073)
    at https://simrbase.stowers.org/jbrowse/dist/0.bundle.js:1:20377
    at https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:514577
    ----------------------------------------
Error
    at c.then.h.then (https://simrbase.stowers.org/jbrowse/dist/0.bundle.js:1:42476)
    at Object.makeTrackLabel (https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:828626)
    at Object.setViewInfo (https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:263250)
    at Object.d (https://simrbase.stowers.org/jbrowse/dist/0.bundle.js:1:13514)
    at Object.setViewInfo (https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:320524)
    at Object.<anonymous> (https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:514073)
    at https://simrbase.stowers.org/jbrowse/dist/0.bundle.js:1:20377
    at https://simrbase.stowers.org/jbrowse/dist/1.bundle.js:1:514577
    at c (https://simrbase.stowers.org/jbrowse/dist/main.bundle.js:1:2962)
    at e (https://simrbase.stowers.org/jbrowse/dist/main.bundle.js:1:2140)"
r @ 0.bundle.js:14
```

Thank you,
Sofia

**Comment by cmdcolin** [comment]
Hi there, I think if you pull the latest code from this repo you'll get a fix for this error

**Comment by srobb1** [comment]
Will I need to rerun ./setup.sh ?

**Comment by cmdcolin** [comment]
Ya, the latest versions of jbrowse (all versions post 1.13.0) require rebuilding plugins. You can use ./setup.sh to do that after any plugin change

**Comment by srobb1** [comment]
Thanks @cmdcolin! The error is gone!
